//Menu Set Preferences ( 1.13)
//
//
menuSet -permanent 1 -hotBoxVisible 1 -label "Common" -menuArray { "mainFileMenu", "mainEditMenu", "mainCreateMenu", "mainSelectMenu", "mainModifyMenu", "mainDisplayMenu", "mainWindowMenu" } commonMenuSet;
menuSet -moveMenuSet commonMenuSet 0;
menuSet -permanent 0 -hotBoxVisible 1 -label "Modeling" -menuArray { "mainMeshMenu", "mainEditMeshMenu", "mainMeshToolsMenu", "mainMeshDisplayMenu", "mainCurvesMenu", "mainSurfacesMenu", "mainDeformMenu", "mainUVMenu", "mainGenerateMenu" } modelingMenuSet;
menuSet -moveMenuSet modelingMenuSet 1;
menuSet -permanent 0 -hotBoxVisible 1 -label "Rigging" -menuArray { "mainRigSkeletonsMenu", "mainRigSkinningMenu", "mainRigDeformationsMenu", "mainRigConstraintsMenu", "mainRigControlMenu" } riggingMenuSet;
menuSet -moveMenuSet riggingMenuSet 2;
menuSet -permanent 0 -hotBoxVisible 1 -label "Animation" -menuArray { "mainKeysMenu", "mainPlaybackMenu", "mainVisualizeMenu", "mainDeformationMenu", "mainConstraintsMenu" } animationMenuSet;
menuSet -moveMenuSet animationMenuSet 3;
menuSet -permanent 0 -hotBoxVisible 1 -label "FX" -menuArray { "mainParticlesMenu", "mainFluidsMenu", "mainNClothMenu", "mainHairMenu", "mainNConstraintMenu", "mainNCacheMenu", "mainFieldsSolverMenu", "mainDynEffectsMenu", "mainBifrostMenu" } dynamicsMenuSet;
menuSet -moveMenuSet dynamicsMenuSet 4;
menuSet -permanent 0 -hotBoxVisible 1 -label "Rendering" -menuArray { "mainShadingMenu", "mainRenTexturingMenu", "mainRenderMenu", "mainCartoonMenu", "mainStereoMenu" } renderingMenuSet;
menuSet -moveMenuSet renderingMenuSet 5;
