//Maya Preference 2016 (Release 1)
//
//
evalDeferred("autoLoadPlugin(\"\", \"mayaHIK\", \"mayaHIK\")");
evalDeferred("autoLoadPlugin(\"\", \"GamePipeline\", \"GamePipeline\")");
evalDeferred("autoLoadPlugin(\"\", \"CloudImportExport\", \"CloudImportExport\")");
evalDeferred("autoLoadPlugin(\"\", \"tiffFloatReader\", \"tiffFloatReader\")");
evalDeferred("autoLoadPlugin(\"\", \"bifrostvisplugin\", \"bifrostvisplugin\")");
evalDeferred("autoLoadPlugin(\"\", \"ikSpringSolver\", \"ikSpringSolver\")");
evalDeferred("autoLoadPlugin(\"\", \"ik2Bsolver\", \"ik2Bsolver\")");
evalDeferred("autoLoadPlugin(\"\", \"xgenToolkit\", \"xgenToolkit\")");
evalDeferred("autoLoadPlugin(\"\", \"AbcExport\", \"AbcExport\")");
evalDeferred("autoLoadPlugin(\"\", \"gameFbxExporter\", \"gameFbxExporter\")");
evalDeferred("autoLoadPlugin(\"\", \"VectorRender\", \"VectorRender\")");
evalDeferred("autoLoadPlugin(\"\", \"OpenEXRLoader\", \"OpenEXRLoader\")");
evalDeferred("autoLoadPlugin(\"\", \"lookdevKit\", \"lookdevKit\")");
evalDeferred("autoLoadPlugin(\"\", \"Unfold3D\", \"Unfold3D\")");
evalDeferred("autoLoadPlugin(\"\", \"Type\", \"Type\")");
evalDeferred("autoLoadPlugin(\"\", \"mayaCharacterization\", \"mayaCharacterization\")");
evalDeferred("autoLoadPlugin(\"\", \"modelingToolkit\", \"modelingToolkit\")");
evalDeferred("autoLoadPlugin(\"\", \"MayaMuscle\", \"MayaMuscle\")");
evalDeferred("autoLoadPlugin(\"\", \"rotateHelper\", \"rotateHelper\")");
evalDeferred("autoLoadPlugin(\"\", \"DirectConnect\", \"DirectConnect\")");
evalDeferred("autoLoadPlugin(\"\", \"matrixNodes\", \"matrixNodes\")");
evalDeferred("autoLoadPlugin(\"\", \"AbcImport\", \"AbcImport\")");
evalDeferred("autoLoadPlugin(\"\", \"BifrostMain\", \"BifrostMain\")");
evalDeferred("autoLoadPlugin(\"\", \"autoLoader\", \"autoLoader\")");
evalDeferred("autoLoadPlugin(\"\", \"sceneAssembly\", \"sceneAssembly\")");
evalDeferred("autoLoadPlugin(\"\", \"gpuCache\", \"gpuCache\")");
evalDeferred("autoLoadPlugin(\"\", \"Substance\", \"Substance\")");
evalDeferred("autoLoadPlugin(\"\", \"OneClick\", \"OneClick\")");
evalDeferred("autoLoadPlugin(\"\", \"shaderFXPlugin\", \"shaderFXPlugin\")");
evalDeferred("autoLoadPlugin(\"\", \"bifrostshellnode\", \"bifrostshellnode\")");
evalDeferred("autoLoadPlugin(\"\", \"ArubaTessellator\", \"ArubaTessellator\")");
evalDeferred("autoLoadPlugin(\"\", \"xgenMR.py\", \"xgenMR\")");
evalDeferred("autoLoadPlugin(\"\", \"quatNodes\", \"quatNodes\")");
evalDeferred("autoLoadPlugin(\"\", \"fbxmaya\", \"fbxmaya\")");
