
    menuItem
        -label "Perspective View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchModelView persp" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem95;

    menuItem
        -label "Side View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchModelView side" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "E" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem96;

    menuItem
        -label "Front View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchModelView front" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "S" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem97;

    menuItem
        -label "Top View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchModelView top" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "W" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem98;

    menuItem
        -label "Left View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "MTviewChange(\"left\", \"-ls\");" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -version "2014" 
        -longDivider 1
        menuItem99;

    menuItem
        -label "Back View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "MTviewChange(\"back\", \"-b\");" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -version "2014" 
        -longDivider 1
        menuItem100;

    menuItem
        -label "Bottom View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "MTviewChange(\"bottom\", \"-bo\");" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -version "2014" 
        -longDivider 1
        menuItem101;

    menuItem
        -label "Hotbox Style" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem102;

        menuItem
            -label "Zones and Menu Rows" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "hotBox -dh" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 0
            -sourceType "mel" 
            -longDivider 1
            menuItem103;

        menuItem
            -label "Zones Only" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "hotBox -dzo" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 0
            -sourceType "mel" 
            -longDivider 1
            menuItem104;

        menuItem
            -label "Center Zone Only" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "hotBox -dco" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 0
            -sourceType "mel" 
            -longDivider 1
            menuItem105;

    setParent -m ..;

setParent -m ..;

