
    menuItem
        -label "Outliner" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType Outliner" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem67;

    menuItem
        -label "Graph Editor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType GraphEditor" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "E" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem68;

    menuItem
        -label "Dope Sheet" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType DopeSheet" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem69;

    menuItem
        -label "Hypergraph" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType Hypergraph" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "S" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem70;

    menuItem
        -label "Node Editor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType NodeEditor" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem71;

    menuItem
        -label "Hypershade" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType Hypershade" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "W" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem72;

    menuItem
        -label "Render View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType RenderView" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem73;

    menuItem
        -label "Sets" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchPanelToType SetEditor" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem74;

setParent -m ..;

