
    menuItem
        -label "NURBS Mask" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setSelectMode nurbsModeling NURBS" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem87;

    menuItem
        -label "Hierarchy" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setSelectMode hierarchy Hierarchy" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem88;

    menuItem
        -label "Animation Mask" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setSelectMode animation Animation" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "E" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem89;

    menuItem
        -label "Deformations Mask" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setSelectMode deformations Deformations" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem90;

    menuItem
        -label "Dynamics Mask" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setSelectMode dynamics Dynamics" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "S" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem91;

    menuItem
        -label "Polygons Mask" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setSelectMode polyModeling Polygons" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem92;

    menuItem
        -label "Rendering Mask" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setSelectMode rendering Rendering" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "W" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem93;

    menuItem
        -label "Object/Components" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "if ( `selectMode -q -component` ) { setSelectMode objects Objects; } \t\t\t else { setSelectMode components Components; }" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 0
        -sourceType "mel" 
        -longDivider 1
        menuItem94;

setParent -m ..;

